import streamlit as st
import os

def main():
    st.title("My Streamlit App")

    image_path = "images/logo.png"

    if os.path.exists(image_path):
        st.image(image_path, use_column_width=True, caption="Generated by DALL·E")
    else:
        st.warning(f"Image not found: {image_path}")

if __name__ == "__main__":
    main()
